server:
  port: 8080
  tomcat:
    threads:
      max: 200
      # Esta es la propiedad correcta para versiones modernas de Spring Boot:
      connection-timeout: 120s

gemini:
  api:
    key: ${GEMINI_API_KEY}


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
    async:
      request-timeout: 120000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:volticfit@gmail.com}
    password: ${MAIL_PASSWORD:pnnz onsb dvcb grse}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend:
    url: ${APP_FRONTEND_URL}
  upload:
    path: ${UPLOAD_PATH:uploads/medical-docs}
    clinical-docs: ${UPLOAD_CLINICAL_PATH:uploads/clinical-docs}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: ${JWT_EXPIRATION:3600000}
    recovery-expiration: ${JWT_RECOVERY_EXP:900000}
    recovery-expiration-minutes: 15