spring:
  application:
    name: volticfit

  datasource:
    url: jdbc:mysql://localhost:3306/VolticFit
    username: root
    password:  # Pon tu contraseña aquí si tienes
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # CAMBIO CLAVE: 'validate' solo revisa, no intenta crear nada
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tu_correo@gmail.com}
    password: ${MAIL_PASSWORD:tu_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:4200}
  jwt:
    recovery-expiration: ${JWT_RECOVERY_EXP:900000}

server:
  port: 9090

security:
  jwt:
    secret-key: ${JWT_SECRET:Y29tLnByb3llY3RvLnZvbHRpY2ZpdC5zZWNyZXQua2V5LnZlcnkuc2VjdXJlLmJhc2U2NC5kZW1v}
    # Ojo aquí: tu JwtService busca 'token-expiration', no 'expiration-time'
    token-expiration: ${JWT_EXPIRATION:3600000}
    recovery-expiration: ${JWT_RECOVERY_EXP:900000}